apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: dataservice-failure
  namespace: chaos-demo
spec:
  action: pod-failure
  mode: all
  selector:
    namespaces:
      - chaos-demo
    labelSelectors:
      app: dataservice
  duration: "30s"
