apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: stress-and-delay-workflow
  namespace: chaos-demo
spec:
  entry: entry
  templates:
    - name: entry
      templateType: Serial
      children:
        - stress-cpu
        - network-delay
    - name: stress-cpu
      templateType: StressChaos
      deadline: "5s"
      stressChaos:
        mode: one
        selector:
          namespaces:
            - chaos-demo
          labelSelectors:
            app: backend
        stressors:
          cpu:
            workers: 1
            load: 80
    - name: network-delay
      templateType: NetworkChaos
      deadline: "10s"
      networkChaos:
        action: delay
        mode: all
        selector:
          namespaces:
            - chaos-demo
          labelSelectors:
            app: frontend
        delay:
          latency: "1s"
        direction: to
