apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: mixed-jitter-chaos
  namespace: chaos-demo
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - chaos-demo
    labelSelectors:
      app: frontend
  delay:
    latency: "100ms"
    jitter: "4000ms"
  direction: both
  target:
    selector:
      namespaces:
        - chaos-demo
      labelSelectors:
        app: backend
    mode: all
  duration: "1m"
