apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: heavy-network-delay
  namespace: chaos-demo
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - chaos-demo
    labelSelectors:
      app: backend
  delay:
    latency: "5s"
    jitter: "100ms"
  direction: to
  duration: "1m"
